### ISSUE TITLE
Plugins not loading 

### ISSUE THREAD

**Issue by TheJoe49** [happypandax/happypandax#70] opened 2018-10-31 21:36 UTC
**Describe the bug**
I downloded the two e hentia plugins and put them in to the default plugin folder. Upon starting the server it says that it loaded two plugins, however when I go to the plugin page in the webclient nothing shows up.

**To Reproduce**
No Idea.

**Expected behavior**
Plugin to be seen on the plugin tab.

**Logs**
Debug Log - https://pastebin.com/GNR8YH5S
Plugin Log - https://pastebin.com/qgvaH9yg
Activity Log - https://pastebin.com/BGeiMNkW

**Screenshots**
![screenshot_6](https://user-images.githubusercontent.com/16162727/47819494-ae72f580-dd28-11e8-8ac1-4565d655d293.png)

**Environment:**
 - OS: Windows 10 
 - Browser and browser version: Chrome Version 70.0.3538.77
 - HPX Version 0.4.0

**Comment by observeroftime02** [comment] 2018-10-31 22:18
I can confirm that previously working plugins no longer function.

This is the result of trying to load the metadata plugin:
At first glance the loading of the plugin does not produce any error upon starting the server. It does, however, not show up under installed plugins. Then, when trying to add a gallery it throws the following errors.

Metadata Plugin Log: https://pastebin.com/YVzMZizV
activity log: https://pastebin.com/t5zZzfBa
error log: https://pastebin.com/aJCCCF46
plugin log: https://pastebin.com/5Pvg1jV0

Also, the other two metadata plugins fail to load because they seem to require a server version of happypandax >= 0.5.0

**Comment by twiddli** [comment] 2018-10-31 23:41
Hi, version `0.5.0` will be released in a bit.

**Comment by twiddli** [comment] 2018-10-31 23:58
Fixed in `0.5.0`

**Closed by twiddli** 2018-10-31 23:58 UTC
Labels: bug :beetle:, comp: webclient
