### ISSUE TITLE
Component Tokens for Gallery Scanner not working

### ISSUE THREAD

**Issue by coalsock** [happypandax/happypandax#129] opened 2019-07-30 11:45 UTC
I'm having trouble understanding how the component-tokens for the scanner works. 

Lets say I have the following file path:
D:/Directory/MixedReal/(C87) [Xration (mil)] MIXED-REAL Union (Zeroin) [English] [biribiri].zip

I want the scanner to treat MixedReal as a collection and all the files in it as galleries, so I assume I should input the following into the scanner:
D:/Directory/{collection}/{gallery}

However, the scanner comes up blank when I do so; it does not show any of the galleries I want to be imported into HPX. I'm not certain if I am using the component-tokens incorrectly, could you help with this issue? Thanks!

**Comment by twiddli** [comment] 2019-07-31 09:52
Hello,
I've confirmed that this is indeed not working as intended.

**Comment by twiddli** [comment] 2019-08-28 23:25
this should now be fixed in `v0.11.0`

**Closed by twiddli** 2019-08-28 23:25 UTC
Labels: bug :beetle:, comp: server
