### ISSUE TITLE
Sidebar is limited by height of galleries list

### ISSUE THREAD

**Issue by nonamethanks** [happypandax/happypandax#183] opened 2019-11-03 03:30 UTC
**Describe the issue**
Sometimes the sidebar breaks and is cut off at the height of the gallery list.

**Screenshots**
![image](https://user-images.githubusercontent.com/12946050/68079935-46029c80-fdf2-11e9-872b-4ede035fe123.png)

**Environment:**
Chrome on Windows, latest version.

**Additional context**
Unchecking "position: fixed;" for ".ui.sidebar" in the chrome inspector fixed it for me, but CSS is black magic for me so I don't really know for sure.

**Comment by twiddli** [comment] 2019-11-03 16:18
duplicate of #148

**Closed by twiddli** 2019-11-03 16:18 UTC
Labels: duplicate
